<?php

use Spatie\LaravelSettings\Migrations\SettingsMigration;

class AddReportFormDisclaimerToGeneralSettings extends SettingsMigration
{
    public function up(): void
    {
        $this->migrator->add('general.report_form_disclaimer', "The report form has been generated by the computer and should not contain handwritten information apart from the signature");
    }
}
